# Generated by Django 2.2.4 on 2019-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190810_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='blog/photos', verbose_name='Photo'),
        ),
    ]
