# Generated by Django 2.2.4 on 2019-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191112_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/photos', verbose_name='Photo'),
        ),
    ]
