# Generated by Django 2.2.4 on 2019-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191113_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='iPhone.png', upload_to='static/media/photos'),
        ),
    ]
