# Generated by Django 2.2.4 on 2019-11-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191113_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/iPhone.png', upload_to='media/'),
        ),
    ]
