# Generated by Django 2.2.4 on 2019-11-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191113_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='catalog/photos/iPhone.png', upload_to='catalog/photos'),
        ),
    ]
