# Generated by Django 2.2.4 on 2019-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191113_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='photos/iPhone.jpg', upload_to='photos/'),
        ),
    ]
