# Generated by Django 2.2.4 on 2019-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191113_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/photos/apple.png', null=True, upload_to='media/photos/'),
        ),
    ]
