# Generated by Django 2.2.4 on 2019-11-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20191117_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/photos/apple.png', null=True, upload_to='photos/'),
        ),
    ]
