# Generated by Django 2.2.7 on 2019-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191117_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='photos/apple.png', null=True, upload_to='photos/'),
        ),
    ]
