# Generated by Django 2.2.2 on 2020-12-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20201226_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Цена'),
        ),
    ]
