# Generated by Django 2.2.2 on 2021-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210124_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
