# Generated by Django 2.2.2 on 2021-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210125_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['label']},
        ),
        migrations.AddField(
            model_name='attributetype',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=4, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Attribute'),
        ),
    ]
