# Generated by Django 2.2.2 on 2021-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210126_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Post'),
        ),
    ]
