# Generated by Django 2.2.2 on 2021-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_attributetype_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
