# Generated by Django 2.2.2 on 2021-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_itemattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattributes',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='posts_id', to='blog.Post'),
        ),
    ]
