# Generated by Django 2.2.2 on 2021-01-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210128_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributetype',
            name='item',
        ),
    ]
