# Generated by Django 2.2.2 on 2021-01-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_attributetype_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemattributes',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='attribute',
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='attribute_id',
            field=models.ManyToManyField(blank=True, related_name='attributes_id', to='blog.AttributeType'),
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='attribute_value',
            field=models.ManyToManyField(blank=True, related_name='attributes_value', to='blog.AttributeType'),
        ),
    ]
