# Generated by Django 2.2.2 on 2021-01-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20210131_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattributes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
