# Generated by Django 2.2.2 on 2021-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_itemattributes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Size'),
        ),
    ]
