# Generated by Django 2.2.2 on 2021-02-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20210131_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributes',
            name='slug',
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='slug',
            field=models.ManyToManyField(blank=True, related_name='post_slug', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_type',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.ItemAttributes'),
        ),
    ]
