# Generated by Django 2.2.2 on 2021-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20210208_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributetype',
            name='slug',
        ),
        migrations.AddField(
            model_name='attributetype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
