# Generated by Django 2.2.2 on 2021-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_remove_attributetype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattributes',
            name='slifkf',
            field=models.CharField(default='d', max_length=50),
        ),
    ]
