# Generated by Django 2.2.2 on 2021-03-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_itemattributes_slifkf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributes',
            name='slifkf',
        ),
    ]
