# Generated by Django 2.2.2 on 2021-03-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_remove_itemattributes_slifkf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributes',
            name='slug',
        ),
    ]
