# Generated by Django 2.2.2 on 2021-03-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_remove_itemattributes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
