# Generated by Django 2.2.2 on 2021-03-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_attributetype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemattributes',
            options={'ordering': ['label']},
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='label',
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='size',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='item_id',
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='chose_attr',
            field=models.ManyToManyField(blank=True, related_name='chose_attr', to='blog.AttributeType'),
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='itemattributes',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Size'),
        ),
    ]
