# Generated by Django 2.2.2 on 2021-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20210303_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattributes',
            name='item_id',
            field=models.ManyToManyField(blank=True, related_name='posts_id', to='blog.Post'),
        ),
    ]
