# Generated by Django 2.2.2 on 2021-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_itemattributes_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattributes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
