# Generated by Django 2.2.2 on 2021-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_remove_itemattributes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattributes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
