# Generated by Django 2.2.2 on 2021-03-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_itemattributes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributes',
            name='slug',
        ),
    ]
