# Generated by Django 2.2.2 on 2021-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_itemattributes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributes',
            name='chose_attr',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='slug',
        ),
        migrations.CreateModel(
            name='BoundTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.ManyToManyField(blank=True, related_name='attribute_id', to='blog.AttributeType')),
                ('item_id', models.ManyToManyField(blank=True, related_name='posts_id', to='blog.Post')),
                ('value', models.ManyToManyField(blank=True, related_name='value', to='blog.ItemAttributes')),
            ],
        ),
    ]
