# Generated by Django 2.2.2 on 2021-03-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_auto_20210305_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundtable',
            name='value',
        ),
    ]
