# Generated by Django 2.2.2 on 2021-03-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_remove_boundtable_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundtable',
            name='value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.ItemAttributes'),
        ),
    ]
