# Generated by Django 2.2.7 on 2019-11-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='img/index.jpeg', upload_to='img/'),
        ),
    ]
