# Generated by Django 2.2.7 on 2019-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191123_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/img/index.jpeg', null=True, upload_to='media/img/'),
        ),
    ]
